Month 8/step 2
TrueD14BL0/stellar-burger pull request #4
Opened 2023-02-10 10:46 UTC by TrueD14BL0

2023-02-10 14:41 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали хорошую работу по добавлению DnD и Redux-а в ваш проект, правильно разделили стор на нужные редьюсеры, удобно отображаете процесс перетаскивания элемента, реализовали динамический скроллинг по клику на таб, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Не следует в качестве начального состояния использовать объект ингредиента с пустыми значениями, используйте `null` или `undefined`;
- Не следует использовать поле `__v` для целей счетчика - оно является техническим из БД Mongo;
- Следует всегда указывать массив зависимостей в `useEffect`, т.к. в случае его отсутствия он будет срабатывать при каждом рендере;
- Нельзя изменять переменную `state` в редьюсере, следует её считать константой и создавать её копию. Если изменяется внутренний массив / объект - то сначала создается копия данного массива, а затем уже идет с ним работа и результат добавляется в новую переменную стейта и возвращается из редьюсера;
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента следует приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.
- Не следует использовать при описании `PropTypes.object`, т.к. он позволяет передать абсолютно любой объект, даже если он не соответствует внутренней логике компонента. Опишите ожидаемый объект через `PropTypes.shape`;
- Вместо `PropTypes.array` следует использовать `PropTypes.arrayOf` (см. https://stackoverflow.com/a/62812267), т.к. с помощью него можно конкретизировать, что именно ожидается в компоненте, а в текущем варианте в него можно передать любой объект, что может привести к случайной ошибке.
- Для каждого нового элемента в конструкторе на этапе его добавления в стор следует генерировать уникальный идентификатор в экшн креаторе и использовать его далее, например в качестве значения для `key` при итерации.

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Обратите внимание на форматирование кода, в некоторых файлах присутствуют неточности с отступами и переносами - для упрощения процесса воспользуйтесь встроенными в вашу IDE командами и/или подключите пакет `Prettier` в ваш проект -  это сильно экономит время, а Ваш код будет всегда красив. 

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-02-10 14:41 UTC, randomroot commented on package.json
> +    "@reduxjs/toolkit": "^1.9.2",
🟡 **Можно улучшить:**

Библиотека не используется в рамках проекта, поэтому её можно безопасно удалить из списка зависимостей

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/ingridientObjReducer.js
> +const initialState = {
🔴 **Нужно исправить:**

1) Не следует в качестве начального состояния использовать объект ингредиента с пустыми значениями, используйте `null` или `undefined`. В случае большого количества ключей данная техника будет сложной в поддержке и может приводить к случайным ошибкам.
2) Следует использовать ключ в стейте, в который кладется ингредиент, вместо помещения его полностью, как объект стейта:

```js
const initialState = {
  ingredient: {...}
}
```

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/ingridientsListReducer.js
> +          ++element.__v;
🔴 **Нужно исправить:**

Не следует использовать поле `__v` для целей счетчика - оно является техническим из БД Mongo. Следует добавить отдельное поле в объект или хранить эти значения в рамках отдельного объекта, например:
```js
counters: {
  'id1': 0,
  'id2': 2
}
```

2023-02-10 14:41 UTC, randomroot commented on src/components/App/App.jsx
>    }, )
🔴 **Нужно исправить:**

Следует всегда указывать массив зависимостей в `useEffect`, т.к. в случае его отсутствия он будет срабатывать при каждом рендере. В данном случае вам следует указать пустой массив, т.к. подразумевается запуск только при первом рендере.

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/orderObjReducer.js
> +      /*здесь запускаем лоадер, которого нет*/
🟡 **Можно улучшить:**

Лоадера пока нет, но вы можете записать значение в переменную стейта `loading`, чтобы в будущем, когда он появится - сразу воспользоваться ей для определение статуса

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/orderObjReducer.js
> +  "number": 0
🔴 **Нужно исправить:**

В качестве начального значения следует использовать `null` или `undefined` - в системе может не быть гарантий, что заказ не может иметь нулевой номер :)

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/constructorListReducer.js
> +        state = {...state,
🔴 **Нужно исправить:**

**Здесь и далее по коду:**

Не следует устанавливать значение стейта присваивая значение переменной `state`  - считайте, что она в режиме `read-only` / константа. Новые значения **всегда следует возвращать** из редьюсера (`return newState`)

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/constructorListReducer.js
> +      state.content.splice(action.index,1);
🔴 **Нужно исправить:**

Нельзя изменять переменную `state`, создайте её копию сначала. Если изменяется внутренний массив / объект - то сначала создается копия данного массива, а затем уже идет с ним работа и результат добавляется в новую переменную стейта и возвращается из редьюсера:
```js
const DELETE_SMTH:
  const arrayCopy = [...state.array];
  arrayCopy.splice(index, 1);
  return {
    ...state,
    array: arrayCopy
  }
```

Главный принцип Redux-a - иммутабельность данных, в случае любого изменения - воздействие должно оказываться на копию, а не на исходные данные

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/constructorListReducer.js
> +      state.content.splice(action.secondEl.index,1,firstEl);
🔴 **Нужно исправить:**

Аналогично комментарию выше

2023-02-10 14:41 UTC, randomroot commented on src/services/actions/orderObj.js
> +                    ...constructorList.content.map(item=>item._id)])
🔴 **Нужно исправить:**

Идентификаторы булок следует установить в **начале** и в **конце** массива - также, как они и расположены в бургере.

2023-02-10 14:41 UTC, randomroot commented on src/components/OrderDetails/OrderDetails.jsx
> +  const orderId = "000000" + orderObj.number;
🟡 **Можно улучшить:**

В случае большого номера заказа его длина может не вместится в модальное окно, а пользователю будет сложно отследить и запомнить его из-за начальных нулей

2023-02-10 14:41 UTC, randomroot commented on src/components/MainContent/MainContent.jsx
> +  children: PropTypes.array.isRequired,
🔴 **Нужно исправить:**

Вместо `array` следует использовать `arrayOf` (см. https://stackoverflow.com/a/62812267), т.к. с помощью него можно конкретизировать, что именно ожидается в компоненте, а в текущем варианте в него можно передать любой объект, что может привести к случайной ошибке.

2023-02-10 14:41 UTC, randomroot commented on src/components/IngridientItem/IngridientItem.jsx
> +  item: PropTypes.object.isRequired,
🔴 **Нужно исправить:**

**Здесь и далее по коду:**

Не следует использовать при описании `PropTypes.object`, т.к. он позволяет передать абсолютно любой объект, даже если он не соответствует внутренней логике компонента. Опишите ожидаемый объект через `PropTypes.shape`;

2023-02-10 14:41 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +      dispatch(addIngridientToConstructor(buns[0]));
🟡 **Можно улучшить:**

1) Операции инкремента/декремента связаны с только с добавлением или удалением ингредиента и идут всегда в паре, поэтому их функционал можно разместить в рамках одного экшена - так мы уменьшим кол-во вызовов и гарантируем, что случайно не забудем где-то написать одну из частей.
2) По-умолчанию лучше оставлять поле булки пустым

2023-02-10 14:41 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +      setCurrent('bun');
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/ingridientsListReducer.js
> +      action.ingridientList.forEach(element => {
🔴 **Нужно исправить:**

Следует устанавливать новый список взамен предыдущего, т.к. мы не можем гарантировать, что в элементах при совпадении `id` остаются прежними и предыдущие данные - например изменилась цена

2023-02-10 14:41 UTC, randomroot commented on src/services/reducers/ingridientsListReducer.js
> +      state.map(element => {
🔴 **Нужно исправить:**

**Аналогично ниже и в других редьюсерах где актуально:**

Не следует использовать функцию `map` - она возвращает новый массив в результате своего выполнения и необходима для преобразования одного массива в другой. В данном случае лучше воспользоваться `forEach` или простой конструкцией `for` - в ней вы сможете завершить итерацию сразу как найдете нужный элемент

2023-02-10 14:41 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +              (<BurgerElement item={item} index={index} key={`${item._id}${index}`}/>)
🔴 **Нужно исправить:**

В данном случае значение ключа зависит от `index` а значит для одного и того же ингредиента оно будет изменяться каждый раз, когда он поменяет своё местоположение (ключ уникален, но не стабилен). 

В момент добавления нового элемента в конструктор с помощью, например, библиотеки `uuid` (см. https://www.npmjs.com/package/uuid) генерируйте в экшн креаторе (не в редьюсере) новый идентификатор и добавьте его в отдельное поле внутри объекта ингредиента, а потом переиспользуйте здесь:

```js
const addIngredient() {
  const constrId = uuidv4();
  dispatch(ADD, { constrId, ...ingredient });
}
```

2023-02-10 14:41 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      dispatch(incrimentIngridientCount(item));
🔴 **Нужно исправить:**

Суммарную стоимость не следует вычислять в редьюсере, целесообразно сделать это в селекторе или просто в компоненте, т.к. возможны ошибки, в случае если забыть вызвать данный диспатч, а в случае переноса - подсчёт произойдет гарантированно при изменении стейта.

2023-02-10 18:26 UTC, TrueD14BL0 commented on src/services/reducers/ingridientsListReducer.js
> +          ++element.__v;
Спасибо, про __v не знал, с монго еще не работал. Потому думал, что это будет как раз загрузка количеств. Описания полей не было :-)

2023-02-10 19:30 UTC, TrueD14BL0 commented on src/services/reducers/ingridientsListReducer.js
> +      action.ingridientList.forEach(element => {
Сделал, что бы побороть двойной рендер...

2023-02-10 19:37 UTC, randomroot commented on src/services/reducers/ingridientsListReducer.js
> +      action.ingridientList.forEach(element => {
Двойной рендер вызывает React.StrictMode — это нормально, с ним хуки вызываются дважды (например useEffect), это сделано для отслеживания ошибок выполнения на этапе разработки. Хорошо, что вы отметили это, но в продакшене таких ререндеров не будет, поэтому и необходимости в данных мерах тоже 🐈

2023-02-10 20:21 UTC, TrueD14BL0 commented on package.json
> +    "@reduxjs/toolkit": "^1.9.2",
Compiled with problems:X

ERROR in ./src/services/store/store.js 3:0-51

Module not found: Error: Can't resolve '@reduxjs/toolkit' in 'C:\xampp\htdocs\react\stellar-burger\src\services\store'

оттуда тащится applyMiddleware

2023-02-11 12:52 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остались несколько моментов, которые следует также исправить для сдачи проекта в данном спринте:

- В `constructorListReducer` следует поправить создание копии массива в нескольких экшенах;

**Хорошего вам дня и настроения!** 🐈

2023-02-11 12:52 UTC, randomroot commented on src/services/reducers/constructorListReducer.js
> +      const copy = state.content;
🔴 **Нужно исправить:**

Присвоение другой переменной не создаёт копию, следует использовать `spread` оператор для создания копии массива `const copy = [...state.content]`.
Аналогично ниже.

2023-02-11 12:52 UTC, randomroot commented on src/services/reducers/ingridientsListReducer.js
>        action.ingridientList.forEach(element => {
🟡 **Можно улучшить:**

В данном случае можно как раз применить функцию `map`, которая преобразует входной массив в итоговый:
```js
const newArr = action.ingridientList.map((element) =>({
  ...element,
  qty: 0
}));
```

2023-02-11 15:42 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-02-11 15:43 UTC, merged