Month 9/step 1
TrueD14BL0/stellar-burger pull request #5
Opened 2023-03-11 11:36 UTC by TrueD14BL0

2023-03-11 12:41 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
Что понравилось:
- Есть авторедирект
- При перезагрузке страницы не сбрасывается авторизация
- Созданы компоненты для защиты роутов для авторизованных и не авторизованных юзеров.

Что необходимо исправить:
- Из-за того что у вас у хедера фиксированная ширина появляется горизонтальный скролл на всех страницах. 
<img width="1440" alt="Снимок экрана 2023-03-11 в 15 28 33" src="https://user-images.githubusercontent.com/60173362/224484510-6a866a67-fb04-449c-b820-53dd194af5d4.png">

- Не получается восстановить пароль - при отправке имейла страница просто перезагружается.

https://user-images.githubusercontent.com/60173362/224484631-066273d0-2f2e-44f5-aab1-5dcd650c66eb.mov

- Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
setCookie('name', value, { path: '/' }).
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.

<img width="852" alt="Снимок экрана 2023-03-11 в 15 33 54" src="https://user-images.githubusercontent.com/60173362/224484783-8f2755c4-2e94-460a-8694-2cbebaa46ccb.png">

- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.


Удачных правок!

2023-03-11 12:41 UTC, andryxxa93 commented on src/components/App/App.jsx
> +        <Route path="/login" element={<UnauthRouteElement element={<LoginPage />}/>}/>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-12 05:38 UTC, andryxxa93 commented
Всё супер! Но осталась одна проблема - токен не обновляется при ошибке запроса данных юзера. 
При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

2023-03-12 08:52 UTC, TrueD14BL0 commented
> Всё супер! Но осталась одна проблема - токен не обновляется при ошибке запроса данных юзера. При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

Андрей, добрый день, не удалось получить проблему обновления данных, попробовал подождать, пробовал куку удалять, никаких ошибок не падает, и данные обновляются. У ме6ня происходит 2 запроса на обновление - первый, если кука "кончилась", вторая, если с сервера пришел плохой результат (!data.success).

2023-03-13 09:20 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-13 09:45 UTC, merged